chore: improves setup action

diff --git a/actions/setup/action.yml b/actions/setup/action.yml
--- a/actions/setup/action.yml
+++ b/actions/setup/action.yml
@@ -5,8 +5,18 @@ inputs:
     description: Github token assigned to CI
     required: false
     default: ${{ github.token }}
+  skip_aws:
+    description: If true, skip authenticating with AWS and configuring ECR
+    required: false
+    default: "false"
+  skip_docker:
+    description: If true, skip authenticating to DockerHub
   skip_earthly:
-    description: If true, skip installing and configuring Earthly
+    description: If true, skip installing Earthly and authenticating to Earthly Cloud
+    required: false
+    default: "false"
+  skip_github:
+    description: If true, skip authenticating to GitHub Container Registry
     required: false
     default: "false"
 
@@ -16,6 +26,8 @@ runs:
     # AWS Provider
     - name: Get AWS provider configuration
       id: aws
+      if: inputs.skip_aws  == 'false'
+      #continue-on-error: true
       shell: bash
       run: |
         echo "==== AWS Setup ====="
@@ -26,26 +38,30 @@ runs:
           REGION=$(echo "$BP" | jq -r .global.ci.providers.aws.region)
           REGISTRY=$(echo "$BP" | jq -r .global.ci.providers.aws.registry)
           ROLE=$(echo "$BP" | jq -r .global.ci.providers.aws.role)
-        fi
 
-        echo "region=$REGION" >> $GITHUB_OUTPUT
-        echo "registry=$REGISTRY" >> $GITHUB_OUTPUT
-        echo "role=$ROLE" >> $GITHUB_OUTPUT
+          echo "region=$REGION" >> $GITHUB_OUTPUT
+          echo "registry=$REGISTRY" >> $GITHUB_OUTPUT
+          echo "role=$ROLE" >> $GITHUB_OUTPUT
+        else
+          echo "No configuration found for AWS provider"
+        fi
     - name: Login to AWS
       uses: aws-actions/configure-aws-credentials@v4
-      if: steps.aws.outputs.region  != '' && steps.aws.outputs.role != ''
+      if: steps.aws.outputs.region  != '' && steps.aws.outputs.role != '' && steps.aws.conclusion == 'success'
       with:
         aws-region: ${{ steps.aws.outputs.region }}
         role-to-assume: ${{ steps.aws.outputs.role }}
     - name: Login to ECR
       uses: docker/login-action@v3
-      if: steps.aws.outputs.registry != ''
+      if: steps.aws.outputs.registry != '' && steps.aws.conclusion == 'success'
       with:
         registry: ${{ steps.aws.outputs.registry }}
 
     # Docker Provider
     - name: Get Docker provider configuration
       id: docker
+      if: inputs.skip_docker  == 'false'
+      #continue-on-error: true
       shell: bash
       run: |
         echo "==== Docker Setup ====="
@@ -61,16 +77,18 @@ runs:
             echo "Error: the docker provider secret must map secret values to 'username' and 'password'"
             exit 1
           fi
+
+          echo "::add-mask::$USERNAME"
+          echo "::add-mask::$PASSWORD"
+
+          echo "username=$USERNAME" >> $GITHUB_OUTPUT
+          echo "password=$PASSWORD" >> $GITHUB_OUTPUT
+        else
+          echo "No configuration found for DockerHub provider"
         fi
-
-        echo "::add-mask::$USERNAME"
-        echo "::add-mask::$PASSWORD"
-
-        echo "username=$USERNAME" >> $GITHUB_OUTPUT
-        echo "password=$PASSWORD" >> $GITHUB_OUTPUT
     - name: Login to Docker Hub
       uses: docker/login-action@v3
-      if: steps.docker.outputs.username != '' && steps.docker.outputs.password != ''
+      if: steps.docker.outputs.username != '' && steps.docker.outputs.password != '' && steps.docker.conclusion == 'success'
       with:
         username: ${{ steps.docker.outputs.username }}
         password: ${{ steps.docker.outputs.password }}
@@ -78,6 +96,7 @@ runs:
     # GitHub Provider
     - name: Get GitHub provider configuration
       id: github
+      if: inputs.skip_github  == 'false'
       shell: bash
       run: |
         echo "==== GitHub Setup ====="
@@ -86,12 +105,13 @@ runs:
         GITHUB=$(echo "$BP" | jq -r .global.ci.providers.github.registry)
         if [[ "$GITHUB" != "null" ]]; then
           LOGIN=1
+          echo "login=$LOGIN" >> $GITHUB_OUTPUT
+        else
+          echo "No configuration found for GitHub provider"
         fi
-
-        echo "login=$LOGIN" >> $GITHUB_OUTPUT
     - name: Login to GitHub Container Registry
       uses: docker/login-action@v3
-      if: steps.github.outputs.login
+      if: steps.github.outputs.login && steps.github.conclusion == 'success'
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
@@ -106,42 +126,46 @@ runs:
         echo "==== Earthly Setup ====="
         BP=$(forge dump .)
 
+        VERSION="latest"
+
         EARTHLY=$(echo "$BP" | jq -r .global.ci.providers.earthly)
         if [[ "$EARTHLY" != "null" ]]; then
           ORG=$(echo "$BP" | jq -r .global.ci.providers.earthly.org)
           VERSION=$(echo "$BP" | jq -r .global.ci.providers.earthly.version)
+
+          echo "org=$ORG" >> $GITHUB_OUTPUT
+
+          EARTHLY_CREDS=$(echo "$BP" | jq -r .global.ci.providers.earthly.credentials)
+          if [[ "$EARTHLY_CREDS" != "null" ]]; then
+            SECRET=$(forge secret get --project . global.ci.providers.earthly.credentials)
+            TOKEN=$(echo "$SECRET" | jq -r .token)
+
+            if [[ "$TOKEN" == "null" ]]; then
+              echo "Error: the earthly provider secret must map the secret value to 'token'"
+              exit 1
+            fi
+
+            echo "::add-mask::$TOKEN"
+            echo "token=$TOKEN" >> $GITHUB_OUTPUT
+          else
+            echo "No configuration found for Earthly Cloud provider"
         else
-          VERSION="latest"
+          echo "No configuration found for Earthly Cloud provider"
         fi
 
-        EARTHLY_CREDS=$(echo "$BP" | jq -r .global.ci.providers.earthly.credentials)
-        if [[ "$EARTHLY_CREDS" != "null" ]]; then
-          SECRET=$(forge secret get --project . global.ci.providers.earthly.credentials)
-          TOKEN=$(echo "$SECRET" | jq -r .token)
-
-          if [[ "$TOKEN" == "null" ]]; then
-            echo "Error: the earthly provider secret must map the secret value to 'token'"
-            exit 1
-          fi
-        fi
-
-        echo "org=$ORG" >> $GITHUB_OUTPUT
         echo "version=$VERSION" >> $GITHUB_OUTPUT
-
-        echo "::add-mask::$TOKEN"
-        echo "token=$TOKEN" >> $GITHUB_OUTPUT
     - name: Install Earthly
       uses: earthly/actions-setup@v1
       if: inputs.skip_earthly == 'false'
       with:
         version: ${{ steps.earthly.outputs.version }}
     - name: Login to Earthly Cloud
-      if: steps.earthly.outputs.token != '' && inputs.skip_earthly == 'false'
+      if: steps.earthly.outputs.token != '' && steps.earthly.conclusion == 'success'
       shell: bash
       run: |
         earthly account login --token "${{ steps.earthly.outputs.token }}"
     - name: Set Earthly organization
-      if: steps.earthly.outputs.token != '' && inputs.skip_earthly == 'false'
+      if: steps.earthly.outputs.token != '' && steps.earthly.conclusion == 'success'
       shell: bash
       run: |
         earthly org select "${{ steps.earthly.outputs.org }}"
